// Release trust — checksum + minisign verification for self-update downloads.
//
// Supply-chain story (audit item: releases used to be verified only by their PE
// or ELF magic bytes, i.e. by nothing at all):
//
//  1. every release asset has a sha256 entry in the release's checksums.txt,
//     generated by CI (.github/workflows/build.yml, release job);
//  2. every release asset has a detached minisign signature (<asset>.minisig),
//     produced by scripts/sign_release.sh with the maintainer's PRIVATE key,
//     which lives only in the repo secret MINISIGN_SECRET_KEY — never in git;
//  3. the matching PUBLIC key is baked into this package (MinisignPublicKey) and
//     a downloaded binary is only swapped in when both checks pass.
//
// Verification uses only the standard library: a minisign "Ed" (legacy, non
// hashed) signature is a plain Ed25519 signature over the raw asset bytes, so
// crypto/ed25519 is enough — no third-party minisign dependency, matching this
// repo's "zero needless deps" style.
package update

import (
	"context"
	"crypto/ed25519"
	"crypto/sha256"
	"encoding/base64"
	"encoding/hex"
	"errors"
	"fmt"
	"io"
	"net/http"
	"os"
	"strings"
)

// sha256Hex is the lowercase hex sha256 of b, matching `sha256sum` output.
func sha256Hex(b []byte) string {
	sum := sha256.Sum256(b)
	return hex.EncodeToString(sum[:])
}

// osGetenv is overridable in tests.
var osGetenv = os.Getenv

// minisignPublicKeyPlaceholder is what the embedded key holds until the
// maintainer replaces it (or injects it with -X at build time). It is
// deliberately a NON-empty, obviously-fake value: the "no key configured" state
// must be explicit, never a silent skip.
const minisignPublicKeyPlaceholder = "REPLACE_WITH_BASE64_MINISIGN_PUBLIC_KEY"

// MinisignPublicKey is the base64 minisign public key (the payload of the
// second line of a minisign.pub file: 2-byte algorithm "Ed" + 8-byte key id +
// 32-byte Ed25519 key). Overridable at build time:
//
//	-ldflags "-X github.com/ponygates/icode/internal/update.MinisignPublicKey=<base64>"
//
// PLACEHOLDER: until a real key is baked in, PublicKeyConfigured() is false and
// the auto-update path refuses to install anything (fail closed). See
// scripts/sign_release.sh for key generation and ICODE.md for the policy.
var MinisignPublicKey = minisignPublicKeyPlaceholder

// AllowUnsignedEnv is the explicit escape hatch for developer builds and
// self-hosted setups that intentionally have no key baked in. Setting it to
// "1" lets the updater install a checksum-verified but UNSIGNED binary after
// printing a loud warning. It has no effect once a real key is embedded —
// signature verification is then mandatory, there is no bypass.
const AllowUnsignedEnv = "ICODE_UPDATE_ALLOW_UNSIGNED"

// ErrNoPublicKey means this build has no release key baked in.
var ErrNoPublicKey = errors.New("此构建未内置 minisign 公钥，无法验证发布产物的签名（fail closed）")

// minisign legacy (non-hashed) algorithm magic; "ED" would mean pre-hashed
// (Blake2b-512) which we deliberately do not support — stdlib has no blake2b.
const (
	minisignAlgEd = "Ed"
	minisignAlgED = "ED"
)

// PublicKeyConfigured reports whether this build carries a real minisign key.
func PublicKeyConfigured() bool {
	k := strings.TrimSpace(MinisignPublicKey)
	return k != "" && !strings.HasPrefix(k, "REPLACE_WITH")
}

// embeddedPublicKey decodes MinisignPublicKey into an Ed25519 key + key id.
func embeddedPublicKey() (ed25519.PublicKey, []byte, error) {
	return embeddedPublicKeyFor(MinisignPublicKey)
}

// embeddedPublicKeyFor decodes a base64 minisign public key (bare payload or a
// whole minisign.pub body) into an Ed25519 key plus its 8-byte key id.
func embeddedPublicKeyFor(s string) (ed25519.PublicKey, []byte, error) {
	payload, err := minisignPayload(s)
	if err != nil {
		return nil, nil, fmt.Errorf("内置 minisign 公钥无效: %w", err)
	}
	// 2 alg + 8 key id + 32 key = 42 bytes (tolerate a longer header, the key
	// material is the tail).
	if len(payload) < 42 {
		return nil, nil, fmt.Errorf("内置 minisign 公钥长度 %d 字节，应为 42 字节", len(payload))
	}
	if string(payload[:2]) != minisignAlgEd && string(payload[:2]) != minisignAlgED {
		return nil, nil, fmt.Errorf("内置 minisign 公钥算法为 %q，仅支持 Ed25519（Ed/ED）", string(payload[:2]))
	}
	if string(payload[:2]) == minisignAlgED {
		return nil, nil, errors.New("内置 minisign 公钥是 pre-hashed（ED）类型，请用 minisign 默认（Ed）模式签名")
	}
	keyID := append([]byte(nil), payload[len(payload)-40:len(payload)-32]...)
	pub := append([]byte(nil), payload[len(payload)-32:]...)
	return ed25519.PublicKey(pub), keyID, nil
}

// minisignPayload strips minisign's comment lines and base64-decodes the first
// payload line. Accepts either a bare base64 string or a whole .pub / .minisig
// file body.
func minisignPayload(s string) ([]byte, error) {
	for _, line := range strings.Split(s, "\n") {
		line = strings.TrimSpace(strings.TrimSuffix(line, "\r"))
		if line == "" || strings.HasPrefix(line, "untrusted comment:") ||
			strings.HasPrefix(line, "trusted comment:") {
			continue
		}
		raw, err := base64.StdEncoding.DecodeString(line)
		if err != nil {
			return nil, fmt.Errorf("base64: %w", err)
		}
		return raw, nil
	}
	return nil, errors.New("没有 base64 载荷行")
}

// verifyMinisig checks a detached minisign signature file against raw asset
// bytes and the embedded public key. The main signature is an Ed25519
// signature over the raw bytes; the key id must match the key that signed it.
func verifyMinisig(raw []byte, sigFile []byte) error {
	pub, keyID, err := embeddedPublicKey()
	if err != nil {
		return err
	}
	return verifyMinisigWithKey(raw, sigFile, pub, keyID)
}

// verifyMinisigWithKey is the testable core of verifyMinisig.
func verifyMinisigWithKey(raw, sigFile []byte, pub ed25519.PublicKey, wantKeyID []byte) error {
	payload, err := minisignPayload(string(sigFile))
	if err != nil {
		return fmt.Errorf("minisign 签名文件无效: %w", err)
	}
	// 2 alg + 8 key id + 64 signature = 74 bytes for the main signature.
	if len(payload) < 74 {
		return fmt.Errorf("minisign 签名载荷长度 %d 字节，应为 74 字节", len(payload))
	}
	alg := string(payload[len(payload)-74 : len(payload)-72])
	if alg == minisignAlgED {
		return errors.New("minisign 签名是 pre-hashed（ED）类型；请用 minisign 默认 Ed 模式重新签名")
	}
	if alg != minisignAlgEd {
		return fmt.Errorf("minisign 签名算法 %q 不受支持", alg)
	}
	sig := payload[len(payload)-64:]
	gotKeyID := payload[len(payload)-72 : len(payload)-64]
	if len(wantKeyID) == 8 && string(gotKeyID) != string(wantKeyID) {
		return fmt.Errorf("minisign key id 不匹配（签名 %x ≠ 公钥 %x）——签名不是由内置公钥对应的私钥产生",
			gotKeyID, wantKeyID)
	}
	if !ed25519.Verify(pub, raw, sig) {
		return errors.New("minisign 签名校验失败：资产被篡改，或签名与内置公钥不符")
	}
	return nil
}

// checksumsAsset is the release asset CI publishes over every other asset.
const checksumsAsset = "checksums.txt"

// maxTrustFileBytes caps how much of a trust file (checksums.txt / .minisig) we
// will read — these are tiny by design, so anything larger is hostile or wrong.
const maxTrustFileBytes = 1 << 20

// maxAssetBytes caps the downloaded binary read into memory for verification.
const maxAssetBytes = 64 << 20

// fetchBytes GETs url and returns its body, size-limited.
func fetchBytes(ctx context.Context, url string, limit int64) ([]byte, error) {
	req, err := http.NewRequestWithContext(ctx, http.MethodGet, url, nil)
	if err != nil {
		return nil, err
	}
	req.Header.Set("User-Agent", "iCode-updater")
	resp, err := http.DefaultClient.Do(req)
	if err != nil {
		return nil, err
	}
	defer resp.Body.Close()
	if resp.StatusCode != http.StatusOK {
		return nil, fmt.Errorf("%s: status %d", url, resp.StatusCode)
	}
	body, err := io.ReadAll(io.LimitReader(resp.Body, limit+1))
	if err != nil {
		return nil, err
	}
	if int64(len(body)) > limit {
		return nil, fmt.Errorf("%s: 超过大小上限 %d 字节", url, limit)
	}
	return body, nil
}

// verifyDownloaded runs the release trust checks against a downloaded asset on
// disk. checksums.txt is mandatory; the .minisig file is fetched when present
// (verifyReleaseAsset then decides whether it is required).
func verifyDownloaded(ctx context.Context, path, assetName string, urls map[string]string, w io.Writer) error {
	fi, err := os.Stat(path)
	if err != nil {
		return err
	}
	if fi.Size() > maxAssetBytes {
		return fmt.Errorf("下载文件 %d 字节超过 %d 上限，拒绝校验", fi.Size(), maxAssetBytes)
	}
	raw, err := os.ReadFile(path)
	if err != nil {
		return fmt.Errorf("read downloaded asset: %w", err)
	}

	sumURL := urls[checksumsAsset]
	if sumURL == "" {
		return fmt.Errorf("release 缺少 %s 资产，无法校验 sha256，拒绝安装（详见 %s 的发布说明）", checksumsAsset, Repo)
	}
	sumBody, err := fetchBytes(ctx, sumURL, maxTrustFileBytes)
	if err != nil {
		return fmt.Errorf("下载 %s: %w", checksumsAsset, err)
	}

	var sig []byte
	if sigURL := urls[assetName+".minisig"]; sigURL != "" {
		if b, err := fetchBytes(ctx, sigURL, maxTrustFileBytes); err == nil {
			sig = b
		}
	}
	return verifyReleaseAsset(raw, assetName, string(sumBody), sig, w)
}

// parseChecksums reads a `sha256sum`-style file ("<hex>  <name>", one per line)
// and returns name → lowercase hex. Names are matched case-sensitively, exactly
// as the release asset is named.
func parseChecksums(body string) map[string]string {
	out := map[string]string{}
	for _, line := range strings.Split(body, "\n") {
		line = strings.TrimSpace(strings.TrimSuffix(line, "\r"))
		if line == "" || strings.HasPrefix(line, "#") {
			continue
		}
		// sha256sum separates the digest and the name with two spaces (binary
		// mode) or one space; also accept whitespace and a "*".
		fields := strings.Fields(line)
		if len(fields) < 2 || len(fields[0]) != 64 {
			continue
		}
		name := strings.TrimPrefix(fields[len(fields)-1], "*")
		out[name] = strings.ToLower(fields[0])
	}
	return out
}

// verifyReleaseAsset is the gate the updater runs before swapping in a
// downloaded binary: sha256 from checksums.txt (always required) plus the
// minisign signature (required whenever the build has a key).
//
// warnings receives the loud escape-hatch notice when the signature step is
// skipped because no key is configured and AllowUnsignedEnv is set.
func verifyReleaseAsset(raw []byte, assetName, checksumsBody string, sigFile []byte, w io.Writer) error {
	sums := parseChecksums(checksumsBody)
	want, ok := sums[assetName]
	if !ok {
		return fmt.Errorf("checksums.txt 中没有 %s 的 sha256 条目，拒绝安装", assetName)
	}
	if got := sha256Hex(raw); !strings.EqualFold(got, want) {
		return fmt.Errorf("sha256 校验失败：%s 期望 %s，实际 %s", assetName, want, got)
	}

	if PublicKeyConfigured() {
		if len(sigFile) == 0 {
			return fmt.Errorf("发布产物 %s 缺少 %s.minisig 签名文件，拒绝安装", assetName, assetName)
		}
		return verifyMinisig(raw, sigFile)
	}

	// No key baked in (developer builds). Fail closed by default.
	if osGetenv(AllowUnsignedEnv) != "1" {
		return fmt.Errorf("%w；设置 %s=1 可在明确警告下仅按 sha256 安装", ErrNoPublicKey, AllowUnsignedEnv)
	}
	_, _ = fmt.Fprintf(w, "\n"+
		"!!!!!!!!!!!!!!!!!! 安全警告 SECURITY WARNING !!!!!!!!!!!!!!!!!!\n"+
		"本次构建未内置 minisign 公钥，%s 的签名无法验证。\n"+
		"仅校验了 sha256（checksums.txt）——sha256 只能保证下载完整，\n"+
		"不能证明该产物真的由 iCode 维护者发布。\n"+
		"你通过 %s=1 明确选择了这条不安全路径；正式环境请改用带公钥的官方构建。\n"+
		"!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!\n\n",
		assetName, AllowUnsignedEnv)
	return nil
}
