package tui

import (
	"strings"
	"testing"
)

// TestShareHTMLEscapesScript guards the XSS contract: model/user text is
// escaped before any markup is introduced, so a `<script>` payload survives
// only as inert text.
func TestShareHTMLEscapesScript(t *testing.T) {
	tu := &TUI{theme: "dark", lang: "zh-CN", model: "test-model", version: "0.1.0"}
	msgs := []Message{
		{Role: RoleUser, Content: "看看这个 <script>alert(1)</script>"},
		{Role: RoleAssistant, Content: "危险内容：<img src=x onerror=alert(2)> 已转义"},
	}
	out := tu.buildShareHTML(msgs)
	if strings.Contains(out, "<script>alert(1)</script>") {
		t.Fatalf("raw <script> leaked into share HTML")
	}
	if strings.Contains(out, "<img src=x onerror=") {
		t.Fatalf("raw onerror attribute leaked into share HTML")
	}
	if !strings.Contains(out, "&lt;script&gt;") {
		t.Fatalf("expected escaped script tag:\n%.200s", out)
	}
}

// TestShareHTMLStructure verifies the document skeleton: doctype, embedded
// CSS, user bubble, assistant block, tool <details>, and the footer.
func TestShareHTMLStructure(t *testing.T) {
	tu := &TUI{theme: "dark", lang: "zh-CN", model: "test-model", version: "9.9.9"}
	msgs := []Message{
		{Role: RoleUser, Content: "帮我写个排序"},
		{Role: RoleAssistant, Content: "好的，用 Go 实现：\n\n```go\nfunc main(){}\n```\n\n- 要点一\n- 要点二\n"},
		{Role: RoleTool, Tool: "bash", ToolArgs: "go test ./...", Content: "ok all"},
		{Role: RoleSystem, Content: "已完成"},
	}
	out := tu.buildShareHTML(msgs)
	for _, want := range []string{
		"<!doctype html>",
		"<style>",        // CSS embedded
		`class="bubble"`, // user bubble
		`class="msg ai"`,
		`<details class="tool">`, // tool card
		"go test ./...",          // tool args visible
		"<ul>",                   // list rendered
		"Generated by",           // footer
		"帮我写个排序",                 // title from first user msg
	} {
		if !strings.Contains(out, want) {
			t.Fatalf("share HTML missing %q:\n%.400s", want, out)
		}
	}
}

// TestShareTitleIsFirstUserLine verifies the page title derivation, including
// the 60-rune cap.
func TestShareTitleIsFirstUserLine(t *testing.T) {
	long := strings.Repeat("长", 100)
	got := shareTitle([]Message{
		{Role: RoleSystem, Content: "sys"},
		{Role: RoleUser, Content: long + "\nsecond line"},
	})
	if got != strings.Repeat("长", 60) {
		t.Fatalf("title not capped at 60 runes: %d", len([]rune(got)))
	}
}

// TestMdToHTML verifies the lightweight renderer's core paths: fenced code
// (chroma), heading, bold, inline code, link scheme allow-list.
func TestMdToHTML(t *testing.T) {
	src := "# 标题\n\n**粗体** 和 `代码` 与 [链接](https://example.com)\n\n```go\nfmt.Println(\"hi\")\n```\n\n[危险](javascript:alert(1))"
	out := mdToHTML(src)
	for _, want := range []string{
		"<h1>", "<strong>粗体</strong>", "<code>代码</code>",
		`href="https://example.com"`,
	} {
		if !strings.Contains(out, want) {
			t.Fatalf("mdToHTML missing %q:\n%s", want, out)
		}
	}
	// javascript: href neutralised.
	if strings.Contains(out, "javascript:") {
		t.Fatalf("javascript: href survived:\n%s", out)
	}
	// The fenced Go block is highlighted (chroma emits styled spans).
	if !strings.Contains(out, "<pre") {
		t.Fatalf("fenced code lost its <pre> wrapper:\n%s", out)
	}
}
