#!/usr/bin/env bash
# ============================================================================
# iCode winget manifest tooling — audit item 23 (winget distribution channel).
#
# winget installs are fed by microsoft/winget-pkgs, not this repo; the YAML
# under scripts/winget/<id>/<version>/ is the source copy we regenerate on
# every release and PR upstream. This script is the ONLY sanctioned producer of
# those files, and crucially of their InstallerSha256 — a checksum can never be
# invented, so it is read straight from the release's own checksums.txt.
#
# The hashes here are the SAME checksums.txt that install.sh, internal/update and
# the scoop/homebrew channels consume (see .github/workflows/build.yml release
# job), so all channels agree on exactly one trusted digest per asset.
#
# USAGE
#   scripts/gen_winget_manifest.sh gen <version> <checksums.txt> [outdir]
#       Render the 4-file multi-manifest set for <version> (plain, no leading v)
#       into outdir (default scripts/winget/<id>/<version>), filling every
#       InstallerSha256 from checksums.txt. Aborts if an asset has no entry.
#   scripts/gen_winget_manifest.sh check <dir>
#       Structural self-check: required keys present, every InstallerSha256 is a
#       real 64-hex digest (placeholder all-zeros rejected), filenames share the
#       PackageIdentifier prefix. Runs in CI so we catch obvious errors even
#       without the `winget create` CLI (Windows-only).
#   scripts/gen_winget_manifest.sh verify <dir> <checksums.txt>
#       Cross-check each manifest InstallerSha256 against the release
#       checksums.txt — CI's post-release guarantee that PR'd hashes are real.
# ============================================================================
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
ID="PonyGates.iCode"                 # PackageIdentifier = <Publisher>.<PackageName>
PUBLISHER="PonyGates"
PKGNAME="iCode"
CMD_NAME="icode"
REPO="ponygates/icode"
MANIFEST_VERSION="1.6.0"
SCHEMA_BASE="https://aka.ms/winget-manifest"

# Architecture (winget) ↔ CLI asset (Go/GOARCH) ↔ .exe suffix.
wt_archs=(x64 arm64)
go_archs=(amd64 arm64)

die() { echo "gen_winget_manifest: $*" >&2; exit 1; }

# sha_for_asset: echo the 64-hex digest for $1 from a checksums.txt body ($2).
sha_for_asset() {
    awk -v n="$1" '
        {
            d = $1; name = $2; sub(/^[*]/, "", name);
            if (length(d) == 64 && d ~ /^[0-9a-fA-F]+$/ && name == n) { print tolower(d); found=1; exit }
        }
        END { if (!found) exit 1 }' "$2"
}

installer_url() { # <version> <go-arch>
    echo "https://github.com/${REPO}/releases/download/v$1/icode-cli-windows-$2.exe"
}

# ── gen ─────────────────────────────────────────────────────────────────────
cmd_gen() {
    local version="${1:-}" sums="${2:-}" outdir="${3:-}"
    [ -n "$version" ] && [ -n "$sums" ] || die "usage: gen <version> <checksums.txt> [outdir]"
    case "$version" in v[0-9]*) die "version 不能带前导 v：收到 '$version'" ;; esac
    [ -f "$sums" ] || die "找不到 checksums.txt: $sums"
    outdir="${outdir:-$REPO_ROOT/scripts/winget/$ID/$version}"

    # Compute real hashes up front — refuse to render anything with a missing
    # or fake digest.
    local i arch goarch sha
    declare -A SHAS=()
    for i in "${!wt_archs[@]}"; do
        arch="${wt_archs[$i]}"; goarch="${go_archs[$i]}"
        sha="$(sha_for_asset "icode-cli-windows-$goarch.exe" "$sums")" ||
            die "checksums.txt 没有 icode-cli-windows-$goarch.exe 的 sha256，无法生成真实 hash"
        [ ${#sha} -eq 64 ] || die "$goarch 的 sha256 长度异常: '$sha'"
        SHAS[$arch]="$sha"
        echo "hash: windows/$arch = $sha"
    done

    mkdir -p "$outdir"

    # 1) version manifest (<id>.yaml) — ties the folder together.
    cat > "$outdir/$ID.yaml" <<EOF
# yaml-language-server: \$schema=$SCHEMA_BASE.version.$MANIFEST_VERSION.schema.json
# Generated by scripts/gen_winget_manifest.sh — DO NOT hand-edit the hash fields.
PackageIdentifier: $ID
PackageVersion: $version
DefaultLocale: en-US
ManifestType: version
ManifestVersion: $MANIFEST_VERSION
EOF

    # 2) installer manifest — real InstallerSha256 from checksums.txt.
    {
        echo "# yaml-language-server: \$schema=$SCHEMA_BASE.installer.$MANIFEST_VERSION.schema.json"
        echo "# InstallerSha256 values are generated from the release checksums.txt."
        echo "PackageIdentifier: $ID"
        echo "PackageVersion: $version"
        echo "InstallerType: portable"
        echo "UpgradeBehavior: install"
        echo "ReleaseNotesUrl: https://github.com/${REPO}/releases/tag/v${version}"
        echo "Commands:"
        echo "  - $CMD_NAME"
        echo "Installers:"
        local i2 a2
        for i2 in "${!wt_archs[@]}"; do
            a2="${wt_archs[$i2]}"
            echo "  - Architecture: $a2"
            echo "    InstallerUrl: $(installer_url "$version" "${go_archs[$i2]}")"
            echo "    InstallerSha256: ${SHAS[$a2]}"
        done
        echo "ManifestType: installer"
        echo "ManifestVersion: $MANIFEST_VERSION"
    } > "$outdir/$ID.installer.yaml"

    # 3) default locale (en-US).
    cat > "$outdir/$ID.locale.en-US.yaml" <<EOF
# yaml-language-server: \$schema=$SCHEMA_BASE.defaultLocale.$MANIFEST_VERSION.schema.json
PackageIdentifier: $ID
PackageVersion: $version
PackageLocale: en-US
Publisher: $PUBLISHER
PublisherUrl: https://github.com/${PUBLISHER,,}
PublisherSupportUrl: https://github.com/${REPO}/issues
Author: iCode Contributors
PackageName: $PKGNAME
PackageUrl: https://github.com/${REPO}
License: Apache-2.0
LicenseUrl: https://raw.githubusercontent.com/${REPO}/master/LICENSE
Copyright: Copyright (c) iCode Contributors
CopyrightUrl: https://github.com/${REPO}/blob/master/LICENSE
ShortDescription: Multi-model AI coding agent for the terminal, desktop and VS Code.
Description: |
  iCode is a Go-based AI coding assistant with a terminal UI, a WebView desktop
  app and a VS Code extension sharing one backend. It supports 14 LLM providers
  and 60+ models out of the box, with cache-first token optimisation, tool
  execution behind a permission gate, session persistence in SQLite, MCP client
  support and self-update.
Tags:
  - ai
  - agent
  - cli
  - coding-assistant
  - llm
  - terminal
  - tui
ReleaseNotesUrl: https://github.com/${REPO}/releases
ManifestType: defaultLocale
ManifestVersion: $MANIFEST_VERSION
EOF

    # 4) additional locale (zh-CN) — the project ships full 简体中文 UI.
    cat > "$outdir/$ID.locale.zh-CN.yaml" <<EOF
# yaml-language-server: \$schema=$SCHEMA_BASE.locale.$MANIFEST_VERSION.schema.json
PackageIdentifier: $ID
PackageVersion: $version
PackageLocale: zh-CN
Publisher: $PUBLISHER
PackageName: $PKGNAME
License: Apache-2.0
ShortDescription: 终端、桌面与 VS Code 通用的多模型 AI 编程助手。
Description: |
  iCode 是一款 Go 编写的 AI 编程助手，共享同一后端，提供终端 TUI、WebView 桌面
  应用与 VS Code 扩展三种界面。内置 14 家模型服务商、60+ 模型，缓存优先的 token
  优化，权限门控下的工具执行，SQLite 会话持久化，MCP 客户端与自更新能力。
Tags:
  - ai
  - 编程助手
  - cli
  - tui
ManifestType: locale
ManifestVersion: $MANIFEST_VERSION
EOF

    echo "generated 4 manifests in: $outdir"
    cmd_check "$outdir"
}

# ── check (structural self-validation, no winget CLI needed) ────────────────
cmd_check() {
    local dir="${1:-}"
    [ -n "$dir" ] && [ -d "$dir" ] || die "usage: check <manifest-dir>"
    local id="$ID" fail=0
    local want=( "$id.yaml" "$id.installer.yaml" "$id.locale.en-US.yaml" "$id.locale.zh-CN.yaml" )
    local f
    for f in "${want[@]}"; do
        if [ ! -f "$dir/$f" ]; then echo "FAIL: 缺少文件 $f" >&2; fail=1; continue; fi
        # filename prefix must equal the PackageIdentifier.
        case "$f" in
            "$id".*) : ;;
            *) echo "FAIL: 文件名前缀与 PackageIdentifier 不一致: $f" >&2; fail=1 ;;
        esac
    done

    # every non-comment, non-blank file must declare the same PackageIdentifier.
    for f in "${want[@]}"; do
        [ -f "$dir/$f" ] || continue
        grep -q "^PackageIdentifier: $id\$" "$dir/$f" || { echo "FAIL: $f 缺 PackageIdentifier: $id" >&2; fail=1; }
        grep -q "^ManifestVersion: $MANIFEST_VERSION\$" "$dir/$f" || { echo "FAIL: $f 缺 ManifestVersion" >&2; fail=1; }
    done

    local inst="$dir/$id.installer.yaml"
    if [ -f "$inst" ]; then
        for key in "^PackageVersion:" "^InstallerType:" "^Installers:" "^ManifestType: installer\$" "^ReleaseNotesUrl:"; do
            grep -q "$key" "$inst" || { echo "FAIL: installer 缺字段 $key" >&2; fail=1; }
        done
        # a Commands entry naming the CLI.
        grep -qE "^  - ${CMD_NAME}\$" "$inst" || { echo "FAIL: installer 缺 Commands: $CMD_NAME" >&2; fail=1; }
        # every InstallerSha256 must be exactly 64 hex and NOT a placeholder.
        local hashes bad=0 z
        while IFS= read -r z; do
            hashes="${z#*InstallerSha256: }"
            hashes="${hashes%% *}"
            if ! printf '%s' "$hashes" | grep -qE '^[0-9a-fA-F]{64}$'; then
                echo "FAIL: InstallerSha256 非 64 位十六进制: '$hashes'" >&2; bad=1
            elif printf '%s' "$hashes" | grep -qE '^0{64}$'; then
                echo "FAIL: InstallerSha256 是占位全零，必须来自 checksums.txt" >&2; bad=1
            fi
        done < <(grep 'InstallerSha256:' "$inst")
        [ "$bad" -eq 0 ] || fail=1
        # count of installers must be >= 1 (we ship x64 + arm64).
        local n; n="$(grep -c 'InstallerUrl:' "$inst")"
        [ "$n" -ge 1 ] || { echo "FAIL: installer 没有任何 InstallerUrl" >&2; fail=1; }
    fi

    local ver="$dir/$id.yaml"
    [ -f "$ver" ] && {
        for key in "^PackageVersion:" "^DefaultLocale: en-US\$" "^ManifestType: version\$"; do
            grep -q "$key" "$ver" || { echo "FAIL: version manifest 缺字段 $key" >&2; fail=1; }
        done
    }

    local dl="$dir/$id.locale.en-US.yaml"
    [ -f "$dl" ] && {
        for key in "^PackageLocale: en-US\$" "^Publisher:" "^PackageName:" "^License: Apache-2.0\$" "^ShortDescription:" "^ManifestType: defaultLocale\$"; do
            grep -q "$key" "$dl" || { echo "FAIL: defaultLocale 缺字段 $key" >&2; fail=1; }
        done
    }

    local lz="$dir/$id.locale.zh-CN.yaml"
    [ -f "$lz" ] && {
        for key in "^PackageLocale: zh-CN\$" "^ManifestType: locale\$"; do
            grep -q "$key" "$lz" || { echo "FAIL: locale zh-CN 缺字段 $key" >&2; fail=1; }
        done
    }

    if [ "$fail" -eq 0 ]; then
        echo "check: OK — 4-file set is structurally sound, hashes are real 64-hex"
        return 0
    fi
    echo "check: FAILED" >&2
    return 1
}

# ── verify (manifest hashes must match the release checksums.txt) ───────────
cmd_verify() {
    local dir="${1:-}" sums="${2:-}"
    [ -n "$dir" ] && [ -n "$sums" ] && [ -d "$dir" ] && [ -f "$sums" ] ||
        die "usage: verify <manifest-dir> <checksums.txt>"
    local inst="$dir/$ID.installer.yaml" fail=0 arch goarch want have lineno=0
    for i in "${!wt_archs[@]}"; do
        arch="${wt_archs[$i]}"; goarch="${go_archs[$i]}"
        want="$(sha_for_asset "icode-cli-windows-$goarch.exe" "$sums")" || { echo "FAIL: checksums 缺 windows/$goarch" >&2; fail=1; continue; }
        # pull the InstallerSha256 that follows this arch's InstallerUrl line.
        have="$(awk -v a="Architecture: $arch" '
            index($0,a){seen=1} seen && /InstallerSha256:/ {sub(/.*InstallerSha256: /,""); sub(/ .*/,""); print; exit}' "$inst")"
        if [ "${have,,}" = "${want,,}" ]; then
            echo "verify: windows/$arch sha256 matches checksums.txt"
        else
            echo "FAIL: windows/$arch manifest sha '$have' != checksums '$want'" >&2; fail=1
        fi
    done
    [ "$fail" -eq 0 ] || return 1
    echo "verify: OK — every manifest hash is real and agrees with the release"
}

case "${1:-}" in
    gen)    shift; cmd_gen "$@" ;;
    check)  shift; cmd_check "$@" ;;
    verify) shift; cmd_verify "$@" ;;
    *) sed -n '2,40p' "$0"; exit 1 ;;
esac
